name: Mock Dispatch Deployment API

on:
  workflow_dispatch: 
    inputs:
      targetRef: 
        required: true 
        type: string
      customField: 
        required: true 
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print custom field and targetRef
        run: |
          echo "targetRef received: <${{ inputs.targetRef }}>".
          echo "customField received:  <${{ inputs.customField }}>".

      - name: Checkout with target branch (targetRef)
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.targetRef }} # checkout code from target branch
      
      - name: Simply print data json into console
        run: |
          # mock deployment, modify to do actual deployment
          cat data.json