name: Mock Dispatch Deployment API with pull request number

on:
  workflow_dispatch: 
    inputs:
      pullRequestNumber: 
        required: true 
        type: number
      customField: 
        required: true 
        type: string
      
jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      productionRef: main 
    steps:
      - name: Print custom field and targetRef
        run: |
          echo "pullRequestNumber received: <${{ inputs.pullRequestNumber }}>".
          echo "customField received:  <${{ inputs.customField }}>".

      - name: Check mergeability (Only conflicts not status checks)
        uses: "actions/github-script@v6"
        with:
          script: |
            const { data: pullRequest } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: Number("${{ inputs.pullRequestNumber }}"),
            });

            console.info(JSON.stringify(pullRequest, null, 4))

            if (pullRequest.mergeable === false) {
              core.setFailed('PR is not mergeable due to conflicts');  // set workflow failed
            } else {
              console.log('PR is mergeable');
              const sourceRef = pullRequest.head.ref;
              console.log(`Setting sourceRef environment variable to ${sourceRef}`);
              core.exportVariable('sourceRef', sourceRef);
            }

      - name: Checkout with productionRef
        uses: actions/checkout@v3

      - name: Check source ref contains all productionRef
        run: |
          git fetch origin ${{ env.productionRef }}
          git fetch origin ${{ env.sourceRef }}
          git checkout ${{ env.sourceRef }}
          if git merge-base --is-ancestor ${{ env.productionRef }} HEAD; then
            echo "${{ env.sourceRef }} contains all code from ${{ env.productionRef }} branch (production)."
          else
            echo "${{ env.sourceRef }} does not contain all code from ${{ env.productionRef }} branch (production)."
            exit 1 # set workflow failed
          fi

      - name: Checkout with sourceRef
        uses: actions/checkout@v3
        with:
          ref: ${{ env.sourceRef }} # checkout code from source branch

      - name: Simply print data json into console
        run: |
          # mock deployment, modify to do actual deployment
          cat data.json